version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout

      - restore_cache:
          keys:
            # Restart caching for every new wrapper and add job name (= JDK version) as JDK influences Gradle's caching
            - gradle-repo-v2-{{ .Environment.CIRCLE_JOB }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      # Note: Cannot use `$CIRCLE_WORKING_DIRECTORY` instead of `$(pwd)` because `~` cannot be resolved (unclear why)
      - run:
          command: |
            docker pull connectical/taskd
            docker run -d --name=taskd -p 53589:53589 -v $(pwd)/docker/taskd:/var/taskd connectical/taskd
            docker ps

      - run: ./gradlew --build-cache --scan build

      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-repo-v2-{{ .Environment.CIRCLE_JOB }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - store_test_results:
          path: ./build/test-results

      - run:
          command: |
            ./gradlew jacocoTestReport
            bash <(curl -s https://codecov.io/bash)

      - store_artifacts:
          path: build/reports/cpd
          destination: cpd

      - store_artifacts:
          path: ./build/reports/spotbugs/*.html
          destination: spotbugs

workflows:
  version: 2
  build:
    jobs:
      - build
