name: Java CI

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }} and JDK ${{ matrix.java_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: [8, 9, 10, 11, 12, 13]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v1
      with:
        java-version:  ${{ matrix.java_version }}
        
    - name: Build with Gradle
      run: ./gradlew build
